### ISSUE TITLE
Interface suggestions for 0.7.5

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#146]
Just some feedback on the UI in the latest release:

- Make the save button say "Save" instead of "Save changes?"
- it's strange to me that the "Save" is missing, and the appears when I edit. You could have it disabled, but at least show it from the beginning so I know it's a possibility
- what do you think of defaulting to the sample sheet instead of the config file? Move the config file to the right and Samples to the left.
- The "edit" button under gear icon is a bit confusing; it might be better to just put a pencil icon next to the description and tag and have them edit in-place or something? Also the private key ... not sure here but it's bit confusing as it is
- when you edit the metadata, the modal should disappear.
- Should the "...", gear, and Fork buttons all collapse into a single menu?

**Comment by nleroy917** [comment]
How's stability? Feels more robust now after a couple iterations since the framework shift.

These are all pretty easy tweaks if someone wants to get their hands dirty with react 😀 @khoroshevskyi @ayobi

**Comment by nleroy917** [comment]
- [x] Make the save button say "Save" instead of "Save changes?"
- [x] it's strange to me that the "Save" is missing, and the appears when I edit. You could have it disabled, but at least show it from the beginning so I know it's a possibility
- [x] what do you think of defaulting to the sample sheet instead of the config file? Move the config file to the right and Samples to the left.
- [x] The "edit" button under gear icon is a bit confusing; it might be better to just put a pencil icon next to the description and tag and have them edit in-place or something? Also the private key ... not sure here but it's bit confusing as it is
- [x] when you edit the metadata, the modal should disappear.
- [x] Should the "...", gear, and Fork buttons all collapse into a single menu?

**Comment by nleroy917** [comment]
Expanded things out a bit to consolidate stuff. This is likely solved unless people have more feedback.
