### ISSUE TITLE
New attribute with number values is converted to floating point automatically

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#180]
Steps to reproduce:

1. open a project.
2. add a column and name it in row 1.
3. add a number as a value to one sample. 
4. click save.

Observe that your number value is changed to floating point, eg, `3` is changed to `3.0`

**Comment by nleroy917** [comment]
I think this is resolved in the latest updates... Not sure what the issue was, but I ripped out any and all code on the front end that is tossing around csv strings and replaced it with JSON objects to represent table data. Everything tightened up after that. I'll mark likely solved if you want to check it out and confirm this isn't an issue anymore.

**Comment by nleroy917** [comment]
This was resolved with the `v0.9.x` release
