### ISSUE TITLE
setup_db.sh script missing

### ISSUE THREAD

**Issue by emiliorighi** [pepkit/pephub#232]
Hi, 

I am trying to setup and run pephub locally with docker-compose, but I am having some issues:

I am not able to find the **setup_db.sh** mentioned in the readme.  https://github.com/pepkit/pephub/blob/2c8a73acc70cd6d542b55b3d3066fb6195e90451/README.md?plain=1#L152 

In the docker compose file the db service has a context (./postgres) that is not actually present in the project.
https://github.com/pepkit/pephub/blob/2c8a73acc70cd6d542b55b3d3066fb6195e90451/docker-compose.yaml#L6

Here you mention to run:
https://github.com/pepkit/pephub/blob/2c8a73acc70cd6d542b55b3d3066fb6195e90451/README.md?plain=1#L170

I think it should be **docker-compose** instead of **docker compose**

Can you please help me? 

Kind regards,
Emilio Righi

**Comment by nleroy917** [comment]
hi @emiliorighi!

Thanks for opening up an issue.

You are definitely right that there is no `setup_db.sh` anymore. The documentation is out of date. We actually closed an issue earlier this year that removed this script altogether: https://github.com/pepkit/pephub/issues/81. You can disregard that script.

> In the docker compose file the db service has a context (./postgres) that is not actually present in the project.

Yes, this also was an artifact of the old way we had the database running. I've removed that from the `docker-compose.yaml` file.

> I think it should be docker-compose instead of docker compose

I believe that docker is [migrating away from`docker-compose`](https://docs.docker.com/compose/migrate/) in favor of `docker compose`. This is why I chose to write the docs with `docker compose` instead of `docker-compose`. I think both should work fine, however, and you can just use the one you like.

Admittedly, the `docker compose` deployment received the least priority, so I think the documentation started running behind our deployment changes. I've made a few updates to the documentation, the `Dockerfile`, and the `docker-compose.yaml` file to hopefully get things going for you (#233). Try to do a fresh pull of the repository and let me know if it solves your issues.

_A note: a lot of the "fun" features like authentication, vector search, etc require even more setup - hopefully clearly articulated in the README. This is why we provide a public instance. I'd check out the [docs there](https://github.com/pepkit/pephub#3-optional-github-authentication-client-setup) if you are interested in logging in and adding peps to an account._

Nathan

**Comment by emiliorighi** [comment]
Hi @nleroy917 ,

Thank you so much for your response.

You are definitively right about preferring docker compose over docker-compose, my bad!

I will give it a try and let you know.

Regards,
Emilio Righi
