### ISSUE TITLE
Search result limit

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#242]
It's not clear to me why there's a limit on the search box. I think we could make the search system more intuitive.

**Comment by nleroy917** [comment]
@nsheff do you think that we should just remove the limit? I agree it doesn't make sense to be there

**Comment by nsheff** [comment]
I think it shouldn't be there. But then, will you just request the result pages as they page through them?

Or, does it make more sense to set a distance cutoff, and then show a *number* of "hits"?

**Comment by nleroy917** [comment]
I was looking into this and one of the reasons limit is nice, is because with the vector search, its possible that someone can set a really low score threshold (i.e. a high distance in vector space) and it will return many many many projects

**Comment by khoroshevskyi** [comment]
So in this case we would need pagination of return results, no?

**Comment by nleroy917** [comment]
Made some changes here, I will solicit feedback after an initial release

**Comment by nleroy917** [comment]
### Search update:
Searching is the last thing I want to work on. My goal initially was to *"make it like google"*. To that end, I've gotten rid of all params like `limit` and `score threshold` from the main UI. Unfortunately, Qdrant doesn't have a `count` API like I initially thought:

<img width="854" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/fd72dcfc-2b6a-4278-9590-cbfa4f63127f">

it isn't immediately clear why we can't do this, because I can mess with `score_threshold` to yield different amounts of vectors. A potential workaround is to artificially set the limit to a very high number (10,000) and count the total results, but this is a huge bottleneck in searching. 

Anyways, I was chasing this for awhile and realized that I was doing all of this just to show that "XXX results found" text. So I think for now, I'll just kick this can down the road. Maybe a sufficiently motivated rust club member could take it upon themselves to implement `count` in qdrant  👀 We can track in a new issue #250

**I might stick with traditional pagination, but updates to search are:**
- bubble up key-word matches for direct-accession searching
- simplified UI
- less buggy (it was kind of buggy before)

**Comment by nleroy917** [comment]
Because of the nature of vector search, you can essentially search forever... So I let users keep hitting "more" until there are no more results

**Comment by khoroshevskyi** [comment]
Was fixed in 0.11.8
