### ISSUE TITLE
`load_db.py` fails for PEPs that don't have a config file

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#253]
Just like the title says, if you attempt to load a database up with PEPs where some don't have a config file, it will fail. This comes from #252

**Comment by nleroy917** [comment]
Specific error is:
> NotImplementedError: Project name inference isn't supported on a project that lacks a config file.

**Comment by khoroshevskyi** [comment]
This issue is fixed in peppy0.40.0

For script: https://github.com/pepkit/pephub/blob/master/scripts/load_db.py, it is impossible to upload projects without a config file. In the config file, the user specifies the project name, and since the project name is required, the user should specify it in the config file beforehand.

**Comment by khoroshevskyi** [comment]
Additionally, it is not recommended to upload projects to the database directly using pepdbagent. In this case I would recomend to use pephubClient - https://pypi.org/project/pephubclient/.

**Comment by khoroshevskyi** [comment]
I have updated https://github.com/pepkit/pephub/blob/dev/scripts/load_db.py, so now it user should be able to upload PEPs only with csv file. Latest updates are on dev branch

**Comment by nleroy917** [comment]
I believe that this has been solved, no?

**Comment by khoroshevskyi** [comment]
This issue was solved in peppy0.40.0
