### ISSUE TITLE
nice landing page for api

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#265]
with the api now separated from the UI, it would be nice to have at least some "success" message when you connect to the api, or direct you to the API docs, or something. right now it just says 

```
{"detail":"Not Found"}
```

which is confusing.

**Comment by nleroy917** [comment]
I added a return payload for the [base-base](https://pephub-api.databio.org/) route (as opposed to the true base at `/api/v1`). I suppose we could make it an HTML page, although I am slightly partial to a JSON payload because it signals to me that this is an API that should only be interacted with programmatically.

**Comment by nsheff** [comment]
what happened to the link to the swagger interface?

I am wanting to go to the API from the main UI page, but I can't find a way there.

**Comment by nsheff** [comment]
This is what it says now:

![image](https://github.com/pepkit/pephub/assets/5271009/40a88fd6-2f5a-4ead-9ae6-2709e44f67ba)

That's fine with me, I'll close this issue.
