### ISSUE TITLE
Pinned version requirements

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#29]
Is there a reason you're pinning the version of every dependency here ?  https://github.com/pepkit/pephub/blob/master/requirements/requirements-all.txt

I am not a fan of pinning versions in requirement files -- I prefer at least generally to use minimum bounds, as it makes it more flexible when things get upgraded, I don't have pip yelling at me

Also, this dependency list is extreme, many of these would be covered by sub-dependencies... see, for example, how we usually do it:

https://github.com/refgenie/refgenie/blob/master/requirements/requirements-all.txt

**Comment by nleroy917** [comment]
Hm. That is a big dependency list. It's simply the output of  `pip install freeze > requirements.txt`. I've always done that to ensure that dependencies are upgraded when I want them to be and a build doesn't fail because a new version of a package was released with breaking changes.

[`pipreqs`](https://github.com/bndr/pipreqs) is another option. Are reqs files typically manually curated for our packages?

**Comment by nsheff** [comment]
Yes, we're manually curating them. In my workflow, requirements pinned to specific versions break things, since each package has it's specific requirement.

**Comment by nleroy917** [comment]
What is an appropriate req file for pephub? So far, I can think of:

```txt
peppy>=0.32
fastapi>=0.77.1
eido>=0.1.5
logmuse>=0.2.7 
```

**Comment by nsheff** [comment]
What I do is basically create a file like that, and then update as needed -- the testing github actions will fail if the requirements aren't correct.
