### ISSUE TITLE
UI glitch reloads data on save

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#340]
If you add a sample, and then click save, then there's a UI glitch:

it first *removes* the sample from the table.
then it *updates* the table to replace the same back, once the save is complete.

This seems dangerous to me, because if the save doesn't complete, you may have lost the temporary work you were just adding in.

Instead, I suggest you *don't* remove the sample and then replace it. Just leave the display as is.

**Comment by nleroy917** [comment]
> Instead, I suggest you don't remove the sample and then replace it. Just leave the display as is.

I don't think it's intentionally removing or replacing anything.. also this is super new behavior I have never seen before, so I am not sure why this would be occuring

**Comment by nleroy917** [comment]
The reason there is a "glitch" is that when we make a "save," we invalidate all the requests related to the project. I.e. we tell the application to refetch data about this project because its been changed and we need to get the most recent version of it **across the app** (it keeps things in sync).

So it glitches because when you hit *save*, the query is invalidated, the old data appears, and then the new data comes back in from the server. This can sort of be circumvented by using the `queryClient.setQueryData` function. We can take the new data the user gave us and manually set it across the app (an optimistic update).

Then when the fresh data comes from the server, it gets replaced (but it seems like nothing happened since its the same data anyways).

The weird thing is... this was **never** an issue until very recently. So something odd is occurring that is causing the Sample Table component to fall back on the old data when we hit save, and invalidate the query. Not sure why though.

**Comment by nleroy917** [comment]
Anyways.... its "solved" i guess, but the root cause still can't be traced

**Comment by nsheff** [comment]
Hmm. I'm not sure about that. Shouldn't React be handling that behind the scenes?  Are you storing the table content in a state variable?
