### ISSUE TITLE
Pasting csv file into pephub yields error

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#345]
![image](https://github.com/pepkit/pephub/assets/5271009/fac8f4ac-8c86-4df1-98c5-b8b46e03b373)

When trying to paste a CSV copied from another program, I got this error. It doesn't happen every time, so I'm not sure what triggered it this time.

**Comment by nleroy917** [comment]
![Jul-17-2024 09-57-05](https://github.com/user-attachments/assets/d2cb5883-dd34-4f92-a9dc-4b9d8674213b)

The linked-list implementation of the new database requires a `ph_id` column to be in the data so we can link things up in the database. However, pasting in data will **blow past this column nd overwrite it** if what you are pasting is **larger** than your current table. this is an issue because it removes that `ph_id` column entirely and the server will respond in error if that column doesn't exist.

I don't know how to deal with this and it probably just needs to be a disussion

**Comment by nleroy917** [comment]
All `onPaste` callbacks are gone now, so this shouldn't be an issue anymore...
