### ISSUE TITLE
Add the ability to edit PEPs and sample tables

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#69]
it would be extremely advantageous if users could edit their PEPs right on the website. To make this happen, we should add two things: 1.) A sample table editor, and 2.) a yaml file editor.

**Comment by nleroy917** [comment]
@nsheff I have a basic layout set up. I might need assistance with some of the javascript calls and keeping data on the UI in sync with the server... E.g. if I toggle the project to private, we need to change it locally and change it on the server.

**Comment by nsheff** [comment]
The CSV and yaml editors are now populating correctly. 

Do you need any other help with this issue?

**Comment by nleroy917** [comment]
I believe that @Khoroshevskyi is working on this right now. Here is a [discussion](https://github.com/pepkit/pepdbagent/issues/59#issuecomment-1360866898)

Basically, we need update the UI to do two things:
1) Submit the edit requests to the server
2) reflect the changes locally (which it does, just update some UI elements like button disables, etc)

**Comment by nleroy917** [comment]
This is really close. Its a bit buggy and the code could be cleaner. I need error handling on the UI, but otherwise this is close.

**Comment by nleroy917** [comment]
Two small issues preventing this all from working:

1. Editing the sample table causes a duplication of the `sample_name` column. I believe this is an issue with `peppy` and I will open a corresponding issue. But I think the `Project().from_pandas()` method has a bug. I will try to create a reproducible example.
2. There is a discrepancy between the `pepdbagent` Project model and the API for the `update_item` method: `Project` uses the key `is_private`, while the `update_item` `dict` requires a `private` key. This messes with some things, and I can probably hard-code a fix, but I'd rather not.

@Khoroshevskyi if these are addressed, then things will basically be complete.

**Comment by nleroy917** [comment]
@Khoroshevskyi here is the issue I opened in `peppy` with a reproducible example: https://github.com/pepkit/peppy/issues/424

**Comment by khoroshevskyi** [comment]
@nleroy917 
1. It's weird behavior. I think problem is somewhere in pandas, I will look at it. 
2. Yes, I agree, it's confusing, and we should stick to one name. I will change all variable to: `is_private`

------
I looked into new pephub code and have to comment related to this issue:
1) Do not use `to_csv` function to get csv table! (`project.sample_table.to_csv()`). `sample_table` is already processed data, therefore you can't use processed data to change raw data. In this case you should use: `_sample_df` variable from peppy.Project object.

2) Edit table (with `sample_table` content) incorrectly separates columns.
(Don't have good example yet:( )

3) I would suggest to be consistent and use function: `from_dict`, instead of `from_pandas`. (In code version, you are using once from_dict, and once from_pandas. There is no huge difference, but It would be good to use one way of initiating project everywhere)
https://github.com/pepkit/pephub/blob/e3f15f4c7ca797a2aa79d5bc04032ee380f02c97/pephub/routers/api/v1/project.py#L89
https://github.com/pepkit/pephub/blob/e3f15f4c7ca797a2aa79d5bc04032ee380f02c97/pephub/routers/api/v1/project.py#L126

**Comment by nleroy917** [comment]
I think that this is done if people want to test (and break it)

**Comment by nleroy917** [comment]
This is working and should be solved with `v0.5.0` release #80
